# Generated by Django 3.2.14 on 2023-01-12 06:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(default='Aqua', max_length=255)),
                ('last_name', models.CharField(default='User', max_length=255)),
                ('phone_no', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(default='', max_length=200)),
                ('sic_gst_code', models.CharField(default='', max_length=200)),
                ('pan_no', models.CharField(default='', max_length=200)),
                ('address_one', models.TextField(default='')),
                ('address_two', models.TextField(default='')),
                ('pincode', models.IntegerField(default=0)),
                ('website', models.URLField(default='')),
                ('username', models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'put valid username', 'username is invalid')], verbose_name='username')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_term_accepted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=400, null=True)),
                ('image', models.FileField(null=True, upload_to='user_images')),
                ('images', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_images', to='accounts.user')),
            ],
        ),
    ]
